# theme config
set -g message-style "bg=#00346e, fg=#ffffd7"        # tomorrow night blue, base3

set -g status-style "bg=#00346e, fg=#ffffd7"   # tomorrow night blue, base3
set -g status-left "#[bg=#0087ff] ❐ #S "       # blue
set -g status-left-length 400
#set -g status-right "#{?client_prefix, ~ , } #[bg=#0087ff] #h #{battery_status_bg} #{battery_icon} #{battery_percentage} #{battery_remain} #[bg=#dc144c] %Y-%m-%d %H:%M"
set -g status-right "#[bg=#dc144c] %Y-%m-%d %H:%M"
set -g status-right-length 400

set -wg window-status-format " #I #W"
set -wg window-status-current-format " #I #W #F"
set -wg window-status-separator " "
set -wg window-status-current-style "bg=#dc143c"
set -wg window-status-last-style "fg=red"

# window status alignment
set -g status-justify centre


# The panes {
set -g pane-active-border-style bg=default,fg=colour246
set -g pane-border-style bg=default,fg=colour239
# }

# vi copypaste mode
set-window-option -g mode-keys vi
bind-key -Tcopy-mode-vi 'v' send -X begin-selection
bind-key -Tcopy-mode-vi 'y' send -X copy-selection
bind-key -Tcopy-mode-vi 'r' send -X rectangle-toggle

# reload source file
bind r source ~/.tmux.conf\; display "~/.tmux.conf sourced!"

bind v split-window -h
bind s split-window -v

# enable mouse mode, tmux 2.7 支持双击选词，但是与mouse mode 冲突
set-option -g mouse on

# remove ESC delay
set -sg escape-time 0

# start windows panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-option -g @pane_resize "10"

# others
set-option -g allow-rename off
set-window-option -g automatic-rename on # rename window to reflect current program
set -g status-interval 5

# list of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-yank'
#set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-battery'
#set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# color
set -g default-terminal 'xterm-256color' # replace this with your custom term-info name
set -ga terminal-overrides '*:Tc' # this is for 256 color
# nvim cursor shape
set -ga terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'
# set -ga terminal-overrides ',*:Ss=\eE[%p1%d q:Se=\eE[2 q'

# tmux-yank
set-option -g default-command "reattach-to-user-namespace -l zsh"

set-option -g set-titles on
set-option -g set-titles-string '#T'

# important for neovim autoread
set -g focus-events on


# initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
