require("items.apple")
require("items.yabai")
require("items.spaces")
require("items.front_app")
require("items.calendar")
require("items.battery")
require("items.wifi")
require("items.volume")
require("items.mail")
require("items.networks")
require("items.flow")

require("items.media")
