require("items.apple")
require("items.yabai")
require("items.spaces")
require("items.front_app")
require("items.calendar")
require("items.battery")
require("items.wifi")
require("items.volume")
require("items.mail")
require("items.networks")
require("items.monitor")
require("items.media")

require("items.task")
