#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa


# global settings
# yabai -m config                                 \
#     #external_bar                 all:30:0       \
#     window_placement             second_child   \
#     layout                       float          \
#
# yabai -m config top_padding 5
# yabai -m config bottom_padding 5
# yabai -m config left_padding 5
# yabai -m config right_padding 5
# yabai -m config window_gap 10

# === Tiling setting ===

yabai -m config layout                      bsp

yabai -m config top_padding                 5
yabai -m config bottom_padding              5
yabai -m config left_padding                5
yabai -m config right_padding               5
yabai -m config window_gap                  10

# yabai -m config mouse_follows_focus         off
# yabai -m config focus_follows_mouse         off

# yabai -m config window_topmost              off
# yabai -m config window_opacity              off
# yabai -m config window_shadow               float
#
yabai -m config window_shadow float
yabai -m config window_opacity on
# yabai -m config active_window_opacity       0.95
# yabai -m config normal_window_opacity       0.95
# yabai -m config split_ratio                 0.50
#
# yabai -m config auto_balance                off

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize
yabai -m config external_bar 		    all:25:0

# ===== Rules ==================================
yabai -m rule --add app!="^(kitty|Google Chrome|iTerm2|微信|钉钉)$" manage=off
yabai -m rule --add app="^微信$" title!="^微信 \(聊天\)$" manage=off
yabai -m rule --add app="^钉钉$" title!="^钉钉$" manage=off
yabai -m rule --add app="^(kitty|Google Chrome|iTerm2|微信|钉钉|QQ音乐)$" opacity=0.95
# yabai -m rule --add app="^Discord$" opacity=1.0
# yabai -m rule --add app="^系统设置$" opacity=1.0
# yabai -m rule --add app="^Finder$" manage=off
# yabai -m rule --add app="^OpenVPN$" manage=off
yabai -m rule --add app=".*" layer=normal

yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
# yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
# yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
# yabai -m signal --add event=window_focused action="sketchybar -m --trigger window_focus &> /dev/null"
# yabai -m signal -add event=window_minimized action="sketchybar -m --trigger space_windows_change &> /dev/null"
# yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger title_change &> /dev/null"
# yabai -m signal --add event=window_destroyed action="yabai -m window --focus prev || yabai -m window --focus first"
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus recent || yabai -m window --focus first"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus recent || yabai -m window --focus first"
#
# float system preferences

# borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=2.0 whitelist="kitty,Google Chrome,iTerm2,WeChat,DingTalk" &

echo "yabai configuration loaded.."

